/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JLabel;
import javax.swing.JTable;

/**
 * The GameTablePanel is a JPanel containing the JTable that displays the game
 * board.
 *
 */
public class GameTablePanel extends javax.swing.JPanel {

    /**
     * Creates new form GameTablePanel.
     *
     */
    public GameTablePanel() {
        
        initComponents();
        
        gameTable.setDefaultRenderer(Object.class,
            (JTable table, Object value, boolean isSelected, boolean hasFocus, int row, int column) -> {
                //This inner TableCellRenderer class for setting the background for individual cells.
                JLabel comp = new JLabel();
                comp.setOpaque(true);
                if (value.equals(1)) {
                    comp.setBackground(Color.BLACK);
                }
                else {
                    comp.setBackground(Color.WHITE);
                }
                return comp;
            });
    }

    /**
     *
     * @return The JTable that displays the game board.
     */
    public final JTable getTable() {
        return gameTable;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        gameTable = new javax.swing.JTable();

        gameTable.setCellSelectionEnabled(true);
        gameTable.setTableHeader(null);
        jScrollPane1.setViewportView(gameTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable gameTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
